name: Node CI

on:
  push:
    branches:
    - feature/*
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.14.1]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy
      run: |
        npm ci
        npm run build --if-present
        npm test
        npx now --token $NOW_TOKEN
      env:
        CI: true
        NOW_TOKEN: ${{ secrets.now }}
